/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSustainabilityClimateSmartFarmingRouteImport } from './routes/projects/sustainability-climate-smart-farming'
import { Route as ProjectsReforestationRouteImport } from './routes/projects/reforestation'
import { Route as ProjectsMazingiraCommunityDriveRouteImport } from './routes/projects/mazingira-community-drive'
import { Route as ProjectsArtsBasedAwarenessRouteImport } from './routes/projects/arts-based-awareness'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSustainabilityClimateSmartFarmingRoute =
  ProjectsSustainabilityClimateSmartFarmingRouteImport.update({
    id: '/projects/sustainability-climate-smart-farming',
    path: '/projects/sustainability-climate-smart-farming',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsReforestationRoute = ProjectsReforestationRouteImport.update({
  id: '/projects/reforestation',
  path: '/projects/reforestation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsMazingiraCommunityDriveRoute =
  ProjectsMazingiraCommunityDriveRouteImport.update({
    id: '/projects/mazingira-community-drive',
    path: '/projects/mazingira-community-drive',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsArtsBasedAwarenessRoute =
  ProjectsArtsBasedAwarenessRouteImport.update({
    id: '/projects/arts-based-awareness',
    path: '/projects/arts-based-awareness',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/arts-based-awareness': typeof ProjectsArtsBasedAwarenessRoute
  '/projects/mazingira-community-drive': typeof ProjectsMazingiraCommunityDriveRoute
  '/projects/reforestation': typeof ProjectsReforestationRoute
  '/projects/sustainability-climate-smart-farming': typeof ProjectsSustainabilityClimateSmartFarmingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/arts-based-awareness': typeof ProjectsArtsBasedAwarenessRoute
  '/projects/mazingira-community-drive': typeof ProjectsMazingiraCommunityDriveRoute
  '/projects/reforestation': typeof ProjectsReforestationRoute
  '/projects/sustainability-climate-smart-farming': typeof ProjectsSustainabilityClimateSmartFarmingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/arts-based-awareness': typeof ProjectsArtsBasedAwarenessRoute
  '/projects/mazingira-community-drive': typeof ProjectsMazingiraCommunityDriveRoute
  '/projects/reforestation': typeof ProjectsReforestationRoute
  '/projects/sustainability-climate-smart-farming': typeof ProjectsSustainabilityClimateSmartFarmingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/arts-based-awareness'
    | '/projects/mazingira-community-drive'
    | '/projects/reforestation'
    | '/projects/sustainability-climate-smart-farming'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/arts-based-awareness'
    | '/projects/mazingira-community-drive'
    | '/projects/reforestation'
    | '/projects/sustainability-climate-smart-farming'
  id:
    | '__root__'
    | '/'
    | '/projects/arts-based-awareness'
    | '/projects/mazingira-community-drive'
    | '/projects/reforestation'
    | '/projects/sustainability-climate-smart-farming'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsArtsBasedAwarenessRoute: typeof ProjectsArtsBasedAwarenessRoute
  ProjectsMazingiraCommunityDriveRoute: typeof ProjectsMazingiraCommunityDriveRoute
  ProjectsReforestationRoute: typeof ProjectsReforestationRoute
  ProjectsSustainabilityClimateSmartFarmingRoute: typeof ProjectsSustainabilityClimateSmartFarmingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/sustainability-climate-smart-farming': {
      id: '/projects/sustainability-climate-smart-farming'
      path: '/projects/sustainability-climate-smart-farming'
      fullPath: '/projects/sustainability-climate-smart-farming'
      preLoaderRoute: typeof ProjectsSustainabilityClimateSmartFarmingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/reforestation': {
      id: '/projects/reforestation'
      path: '/projects/reforestation'
      fullPath: '/projects/reforestation'
      preLoaderRoute: typeof ProjectsReforestationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/mazingira-community-drive': {
      id: '/projects/mazingira-community-drive'
      path: '/projects/mazingira-community-drive'
      fullPath: '/projects/mazingira-community-drive'
      preLoaderRoute: typeof ProjectsMazingiraCommunityDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/arts-based-awareness': {
      id: '/projects/arts-based-awareness'
      path: '/projects/arts-based-awareness'
      fullPath: '/projects/arts-based-awareness'
      preLoaderRoute: typeof ProjectsArtsBasedAwarenessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsArtsBasedAwarenessRoute: ProjectsArtsBasedAwarenessRoute,
  ProjectsMazingiraCommunityDriveRoute: ProjectsMazingiraCommunityDriveRoute,
  ProjectsReforestationRoute: ProjectsReforestationRoute,
  ProjectsSustainabilityClimateSmartFarmingRoute:
    ProjectsSustainabilityClimateSmartFarmingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
